name: Build

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
  workflow_dispatch:

env:
  PRINCIPIA_HEADERS_PROTOBUF: .
  PRINCIPIA_MSVC_PROTOBUF: msvc
  PRINCIPIA_SOLUTION_PROTOBUF: msvc/protobuf.slnf

jobs:
  build:
    runs-on: windows-latest
    strategy:
        matrix:
          configuration: [Debug, Release]
    steps:
    - name: Checkout source files
      uses: actions/checkout@v3

    - name: Initialize build environment
      uses: mockingbirdnest/actions/windows/initialize_build@main
      with:
        configuration: ${{ matrix.configuration }}

    - name: Download abseil artifact
      uses: mockingbirdnest/actions/windows/download_artifact@main
      with:
        name: abseil-cpp
        configuration: ${{ matrix.configuration }}

    - name: Download re2 artifact
      uses: mockingbirdnest/actions/windows/download_artifact@main
      with:
        name: re2
        configuration: ${{ matrix.configuration }}

    - name: Rebuild ${{ matrix.configuration }}
      uses: mockingbirdnest/actions/windows/rebuild@main
      with:
        configuration: ${{ matrix.configuration }}
        solution_glob: ${{ env.PRINCIPIA_SOLUTION_PROTOBUF }}

    - name: Upload artifact
      uses: mockingbirdnest/actions/windows/upload_artifact@main
      with:
        name: protobuf
        configuration: ${{ matrix.configuration }}
        headers_directory: ${{ env.PRINCIPIA_HEADERS_PROTOBUF }}
        solution_directory: ${{ env.PRINCIPIA_MSVC_PROTOBUF }}
